name: Puppeteer Action

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install OpenVPN 3
        id: vpn-setup
        run: |
          sudo apt-get install openvpn -y
        shell: bash
        
      - name: Create VPN configuration file
        run: |
          echo "${{ secrets.VPN_CONFIG }}" | base64 --decode > vpn.ovpn
          
      - name: Create VPN configuration file
        run: |
          sudo openvpn --config vpn.ovpn
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run script
        run: node script.js
